apiVersion: v1
kind: Pod
metadata:
  name: my-firt-pod
  labels:
    name: myapp
spec:
  containers:
  - name: myapp
    image: ngnix
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
